username: admin
password: admin
port: 57400
timeout: 10s
skip-verify: true
encoding: json_ietf

targets:
  leaf1:57400:
  leaf2:57400:

subscriptions:
  srl_if:
    paths:
      - /interface[name=ethernet-1/1]/statistics
      - /interface[name=ethernet-1/1]/oper-state
      - /interface[name=ethernet-1/49]/statistics
      - /interface[name=ethernet-1/49]/oper-state
      - /interface[name=ethernet-1/50]/statistics
      - /interface[name=ethernet-1/50]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 1s

  # srl_bgp_stats:
  #   paths:
  #     - /network-instance[name=*]/protocols/bgp/statistics
  #   mode: stream
  #   stream-mode: sample
  #   sample-interval: 5s

  # srl_ipv4_routes:
  #   paths:
  #     - /network-instance[name=*]/route-table/ipv4-unicast/statistics/
  #   mode: stream
  #   stream-mode: sample
  #   sample-interval: 5s

outputs:
  prom:
    type: prometheus
    listen: :9273
    path: /metrics
    metric-prefix: gnmic
    append-subscription-name: true
    export-timestamps: true
    debug: false
    event-processors:
      - trim-prefixes
  # stdout:
  #   type: file
  #   file-type: stdout
  #   event-processors:
  #     - trim-prefixes

processors:
  trim-prefixes:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - path-base:
            apply-on: "name"
